services:
  - type: web
    name: app-dist-carga-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm install --prefix ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production 