services:
  - type: web
    name: app-dist-carga
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server-simple.js
    envVars:
      - key: NODE_ENV
        value: production 