services:
  - type: web
    name: app-dist-carga
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci --only=production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true 