services:
  - type: web
    name: app-dist-carga-backend
    env: node
    plan: free
    buildCommand: "npm install && cd backend && npm install"
    startCommand: "node backend/server-clean.js"
    databases:
      - name: app-dist-carga-db
        property: connectionString
    envVars:
      - key: NODE_ENV
        value: production

  - type: static_site
    name: app-dist-carga-frontend
    plan: free
    rootDir: frontend
    staticPublishPath: .

databases:
  - name: app-dist-carga-db
    plan: free