services:
  - type: web
    name: app-dist-carga
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: "true" 