services:
  - type: web
    name: app-dist-carga
    env: node
    plan: free
    rootDir: .
    buildCommand: rm -rf node_modules package-lock.json && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 