services:
  - type: web
    name: app-dist-carga-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /api/debug
    envVars:
      - key: NODE_ENV
        value: production 