services:
  # Backend Service (Node.js with Express)
  - type: web
    name: app-dist-carga-backend
    env: node
    plan: free
    rootDir: backend/
    buildCommand: npm install --production
    startCommand: node server-simple.js
    healthCheckPath: /api/debug
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend Service (Static HTML/CSS/JS)
  - type: static
    name: app-dist-carga-frontend
    plan: free
    rootDir: frontend
    staticPublishPath: . 