services:
  - type: web
    name: app-dist-carga-backend
    env: node
    plan: free
    buildCommand: "npm install && cd backend && npm install"
    startCommand: "node backend/server-clean.js"
    envVars:
      - key: NODE_ENV
        value: production